name: Build

on: 
  pull_request:
  push:
    branches-ignore:
      - master
    
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Building Linter Action
        run: |
          cd .github/actions/validate-commit
          npm i 

      - name: Validate Commit Messages
        uses: ./.github/actions/validate-commit

  build:
    runs-on: ubuntu-latest
    needs: [commit]    
    env:
      DOTNET_VERSION: 2.2.110

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Dotnet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release --no-restore

      - name: Generate coverage report
        run : |
          cd ./test/Notifications.PoC.Test
          dotnet test